### ISSUE TITLE
The CategorizationTreeLearner produces leaf nodes having number of data points less leafCountThreshold 

### ISSUE THREAD

**Issue by chunschen** [algorithmfoundry/Foundry#33]
I set the leafCountThreshold to 90k for a very large data set. I then used the model trained to predict the training dataset and found there are many nodes have number of output records much less than the threshold.

In the source code of CategorizationTreeLearner: 

        boolean isLeaf = this.areAllOutputsEqual(data)
            || data.size() <= this.leafCountThreshold
            || (this.maxDepth > 0 && node.getDepth() >= this.maxDepth);

The second condition makes a node have data size less than the leafCountThreshold a leaf node.

**Comment by jbasilico** [comment]
The way the threshold works is that it makes a leaf node if the amount of data in the node is less than or equal to the value. It doesn't guarantee that there is at least that amount of data in the leaf. Instead its a maximum on how many items can go into a leaf.

Are you seeing branch nodes in the tree that less than the leafCountThreshold going through them? If you see that, then it would indicate a bug (assuming the other conditions of hitting the max depth and all the outputs being equal don't trigger).

**Comment by chunschen** [comment]
Thanks for clarifying the issue and sorry that I misunderstood the leafCountThreshold as the minimum leaf size. It is actually the minimum split size according to your comment. Will you consider to have minimum leaf size as an option for controlling the tree growth in the future release?

**Comment by jbasilico** [comment]
Hmm, I suppose that could be added as a parameter somewhere. I guess the implication would be that only splits that maintained the minimum number of examples on each side would be allowed.

**Comment by chunschen** [comment]
Yes. that would be nice if it is added as a new parameter. It provides another level of control for trimming the tree.

**Comment by jbasilico** [comment]
I added a new parameter for those split learners called minSplitSize that can enforce this control.
