### ISSUE TITLE
KMeansClusterer with a CentroidClusterDivergenceFunction crashes when a cluster ends up empty

### ISSUE THREAD

**Issue by Zero3** [algorithmfoundry/Foundry#41]
In KMeansClusterer, the divergences between an element and each of the clusters are measured every iteration. At its core, it happens like this:

     double distance = this.divergenceFunction.evaluate(cluster, element);

When the divergence function is a CentroidClusterDivergenceFunction, evaluate() does this:

    return this.divergenceFunction.evaluate(other, cluster.getCentroid());

However, this throws a NullPointerException when cluster is null (and thus can't be dereferenced at the .getCentroid() call).

A cluster is indeed set to null in KMeansClusterer when all its previous elements have been reassigned to different clusters:

    if (members.size() > 0)
    {
        cluster = this.creator.createCluster(members);
    }
    else
    {
        cluster = null;
    }

**Comment by jbasilico** [comment]
I submitted a fix for this. Let me know if you have any issues with it.

**Comment by Zero3** [comment]
Nice! I will give it a try when I get the chance.

Out of curiosity: What happens to the empty clusters? Do they somehow obtain new samples at some point? Or could more and more clusters end up empty over time?

**Comment by jbasilico** [comment]
For standard K-means, once they become empty, they stay empty.
