### ISSUE TITLE
Improvement in API/documentation clarity with regards to "maximum minimum distance"

### ISSUE THREAD

**Issue by Zero3** [algorithmfoundry/Foundry#42]
I have a small suggestion for improvement of clarity in the API/documentation for the `AgglomerativeClusterer` class: Rename "maximum minimum distance" to "maximum distance".

For example:

> public void setMax~~Min~~Distance(double max~~Min~~Distance)
>
> The maximum ~~minimum~~ distance between clusters that is allowed for the two clusters to be merged. If there are no clusters that remain that have a distance between them less than or equal to this value, then the clustering will halt. To not have this value factored into the clustering, set it to something such as Double.MAX_VALUE.

**Comment by jbasilico** [comment]
Yeah, that is a bit confusing. I'll update it and mark the previous version as deprecated.
