### ISSUE TITLE
Add callback construct for efficient looping over sparse vectors

### ISSUE THREAD

**Issue by jbasilico** [algorithmfoundry/Foundry#46]
Add methods for looping over vectors via a callback where the index and value is passed instead of using an iterator. According to @dbtsai this could be more efficient for sparse vector iteration.

**Comment by jbasilico** [comment]
This is functionality complete. However, one additional performance improvement to get the sparse vector indices without potentially coping them requires a release of MTJ.

**Comment by dbtsai** [comment]
Once MTJ implements getRawIndices, I can benchmark scala's `foreachActive` implemented by a `consumer` with `forEachEntry`. We may consider to implement specialized version of `forEachElement` for `SparseVector` by just looping 0 to getDim, and check if in the indices array. If not, we just return value zero.

**Comment by jbasilico** [comment]
I added the specialized version for SparseVector. You can benchmark it as-is if you make sure to compact all the sparse vectors before you use them. I benchmarked them in Java and it is definitely ~2-4x faster than the iterator for a simple loop (doing sum += i * value).

Looks like the ETA for the MTJ release with the patch is next weekend.

**Comment by dbtsai** [comment]
LGTM!
