### ISSUE TITLE
Protected class AbstractMutableDoubleMap.SimpleEntrySet is exposed through AbstractMutableDoubleMap#entrySet()

### ISSUE THREAD

**Issue by Zero3** [algorithmfoundry/Foundry#50]
The `AbstractMutableDoubleMap.SimpleEntrySet` class is protected, but exposed through the public `AbstractMutableDoubleMap#entrySet()` method. This is a problem, because you can't look at the `SimpleEntrySet` object returned by the `entrySet()` method from "public" when you do not have "public" access to the `SimpleEntrySet` class.

**Comment by jbasilico** [comment]
Yeah, good catch. That return type should be changed to an interface.
