### ISSUE TITLE
StudentTConfidence intervals are inconsistent

### ISSUE THREAD

**Issue by Zero3** [algorithmfoundry/Foundry#58]
In this trivial example, the two confidence interval methods of `StudentTConfidence` only agree with each other for 4 decimals. That doesn't seem accurate enough.

```
System.out.println(StudentTConfidence.INSTANCE.computeConfidenceInterval(Arrays.asList(1D, 2D, 3D), 0.99));
-3.73013950926049 2.0 7.73013950926049 0.99 3
```
```
System.out.println(StudentTConfidence.INSTANCE.computeConfidenceInterval(2, 1, 3, 0.99));
-3.730110858777821 2.0 7.730110858777821 0.99 3
```
Apache's Commons Math agree with the second version for 7 decimals, for what it is worth.

**Comment by jbasilico** [comment]
It looks like the first call is adding the DEFAULT_VARIANCE (1e-5) to the call in the first instance and not the second, to prevent the variance from being 0. That doesn't seem right for most use-cases, but if I change it to use 0 that means if some zero-variance data is put in, there could be some strange outcomes.

**Comment by jbasilico** [comment]
I fixed it by bypassing some of the underlying code and just directly computing the mean and variance for the passed in numbers.
