### ISSUE TITLE
Create a factory for random forests

### ISSUE THREAD

**Issue by jbasilico** [algorithmfoundry/Foundry#6]
The Foundry has support for random forests, however it requires stitching together several components to create the learner. Since it is a very popular method, we should make it easier to get started with it by adding a factory class.

**Comment by Zero3** [comment]
Is there an example of such a stitching available anywhere?

**Comment by jbasilico** [comment]
There is an example in some [slides](http://www.slideshare.net/justinbasilico/lessons-learned-from-building-machine-learning-software-at-netflix) from a talk I gave at a NIPS workshop last year.

Here is a bare-bones example:
```java
        int ensembleSize = 100;
        double baggingFraction = 1.0;
        double fractionOfDimensionsToSample = 0.1;
        int maxDepth = 10;
        int minLeafSize = 10;
        int minSplitSize = 2 * minLeafSize;
        Random random = new Random();
        CategorizationTreeLearner<Vector, Boolean> treeLearner =
            new CategorizationTreeLearner<>(
                new RandomSubVectorThresholdLearner<>(
                    new VectorThresholdInformationGainLearner<>(minLeafSize),
                    fractionOfDimensionsToSample, random),
                maxDepth,
                minSplitSize);
        
        BaggingCategorizerLearner<Vector, Boolean> bagging =
            new BaggingCategorizerLearner<>(treeLearner, ensembleSize,
                baggingFraction, random);
        
        WeightedVotingCategorizerEnsemble<Vector, Boolean, ?> ensemble = 
            bagging.learn(trainData);
```

A few things to note `maxDepth` is the maximum depth enforced on the trees which means you can get up to 2^maxDepth nodes. This is different than what some packages (like R GBM) call depth; in the case of R GBM is is the number of split nodes. Also, the number of dimensions sampled in the random forest is controlled by a percentage, which means you need to make sure that you need to adapt it appropriately to make it sample sqrt(d) or log(d) dimensions per node, depending on the heuristic you are using.

**Comment by Zero3** [comment]
Thanks. Nice slides!

I'm trying to adapt your example, but there seems to be a problem with the generics of the treeLearner variable:

    error: cannot infer type arguments for CategorizationTreeLearner<>;

I'm trying to find the problem, but the generics for these classes are quite complex.

**Comment by Zero3** [comment]
Not sure if this is the correct fix, but i made the error go away by changing

    new VectorThresholdInformationGainLearner<>(minLeafSize)

to

    new VectorThresholdInformationGainLearner<Boolean>(minLeafSize)

**Comment by jbasilico** [comment]
Not sure why it worked in my IDE, but that definition makes sense.

**Comment by Zero3** [comment]
I'm having a hard time getting a good categorization accuracy out of the example above. I tried with a lot of different parameters (including the suggested `double fractionOfDimensionsToSample = Math.sqrt(dataset.numFeatures()) / dataset.numFeatures();`), but I always end up with either very bad results (~10% accuracy) or slightly better than random results (~55% accuracy) for my small test dataset. Using WEKA's Random Forest implementation (with all the default settings), I get an average accuracy of ~85%, which is much better.

Is the example above tested? Is there any test data available where it performs good? Is there any known shortcomings or differences from other implementations (besides those you already mentioned)? I would really like to use Foundry's much cleaner API (compared to WEKA's, at least), but in the end I need usable results :).

**Comment by jbasilico** [comment]
I just put the example together, so I didn't try running that exact set of parameters through. We've used it in the past for data where it performs well, however I haven't used this specific combination in a while. We did add the minLeafSize parameter in 3.4.0 (before only the minSplitSize was used). You can try setting that to 0 and then the minSplitSize to something reasonable and see if that works. I'll look into it a bit more.

**Comment by Zero3** [comment]
Ahhhhh. I just found a big issue with the example: The parameters `maxDepth`, `minLeafSize` and `minSplitSize` are all used in the wrong places according to the APIs they are used in. After moving the parameters around to match the APIs, the corrected version of `treeLearner` looks like this:

	CategorizationTreeLearner<Vector, String> treeLearner = new CategorizationTreeLearner<>
	(
		new RandomSubVectorThresholdLearner<>
		(
			new VectorThresholdInformationGainLearner<String>(minSplitSize),
			fractionOfDimensionsToSample,
			random
		),
		minLeafSize,
		maxDepth
	);

I'll see if I can get better results now the parameters are passed correctly.

**Comment by jbasilico** [comment]
Sorry about that. Actually, I think just the maxDepth and minSplitSize are swapped (the minLeafSize one is related in that the one passed to the tree learner should be at least double the one passed to the splitter). I updated the example.

**Comment by jbasilico** [comment]
Added a RandomForestFactory class.
