### ISSUE TITLE
HELP! (Please) LinearDiscriminantWithBias not compiling evaluate() method

### ISSUE THREAD

**Issue by cogmission** [algorithmfoundry/Foundry#61]
Method references interface that has no implementation! Please help... I can't resolve the implementation within Eclipse.

mvn clean test executes fine...? But I can't compile within my IDE?

Line: 101
gov.sandia.cognition.learning.function.scalar.LinearDiscriminantWithBias.evaluate()

The line calls super.evaluate() but the super implementation is just an interface!?

Please help ?

**Comment by jbasilico** [comment]
Strange that it compiled in ant, maven, and NetBeans but not Eclipse. But it is fixed now.

**Comment by cogmission** [comment]
@jbasilico I think it may be an artifact of Java 8 adherence due to the new need to resolve across default interfaces? Eclipse's compiler always seems to go the "extra" mile (which is not always a good thing...). I've had things that compile in Eclipse that **don't** compile with javac! :-)

Anyway, thanks for your prompt solution!
